import Head from 'next/head'
import Image from 'next/image'
import UploadFile from '../components/UploadFile/UploadFile'
import styles from '../styles/Home.module.css'
import { useState} from "react";
import SelectCarLine from '../components/SelectCarLine/SelectCarLine';
import SelectTestcaseType from '../components/SelectTestcaseType/SelectTestcaseType';
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

export default function Home() {

  const [currentFile, setcurrentFile] = useState();
  const [neWFile, setnewFile] = useState();
  const [carLine, setcarLine] = useState("");
  const [reportType,setreportType] = useState("");
  const [output,setoutput] = useState("");

  const uploadCurrentData = (e) => {
    setcurrentFile(e.target.files[0])
  };

  const uploadNewData = (e) =>{
    setnewFile(e.target.files[0])
  };

  const carLineHandleChange = (e) => {
    console.log(e.target.value);
    setcarLine(e.target.value);
  };

  const reportTypeHandleChange = (e) => {
    console.log(e.target.value);
    setreportType(e.target.value);
  };



  const analyzeButtonCliked = () =>{
    const formData = new FormData();
    //const formData1 = new FormData();

		// formData.append('currentFile', currentFile);
    // formData.append('newFile', neWFile);
    formData.append('carLine',carLine);
    formData.append('reportType',reportType);
    console.log("abc");

    var promise = fetch("https://localhost:44312/weatherforecast",{method:'POST',body: formData});
    promise
    .then(response=>response.text())
    .then(text=>{
      //console.log(text);
      setoutput(text);      
    });
  };




  return (
    <div className={styles.container}>
      <Head>
        <title>Report Gen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Report Generation <a href="">ENG10HV</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <SelectCarLine onSelect={carLineHandleChange} />
          <SelectTestcaseType onSelect={reportTypeHandleChange}/>
        </div>
  
        {/* <UploadFile uploadCurrentData={uploadCurrentData} 
        uploadNewData={uploadNewData}
        analyzeButtonCliked={analyzeButtonCliked} /> */}

    <Stack spacing={2} direction="row">

      <Button variant="contained" onClick={analyzeButtonCliked}>Analyze</Button>

    </Stack>

    <div>{output}</div>





      


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )


}


